### ISSUE TITLE
Does not generate style guide for multiple css files

### ISSUE THREAD

**Issue by Ashot-KR** [jonathantneal/mdcss#18]
Tried it with postcss (cli and grunt task): 
define input source like `styles/*.css` (i have 2 files)
run postcss
randomly get one of result:
1. style giude for the first file with broken html
2. style giude for second file
never get style with docs from both files

**Comment by stephenway** [comment]
@Ashot-KR This is dependent on your mdcss theme, like in mdcss-theme-github you can specify multiple stylesheets in `examples.css` if you give it a map. Aside from that you can edit the main template for the theme and have the page itself load css files manually.

Closing for now because I am unable to see how your configuring your project.
