### ISSUE TITLE
problems with the calculated height of the example:html iframe for floating items

### ISSUE THREAD

**Issue by maoberlehner** [jonathantneal/mdcss#8]
Most likely the height of the iframe is calculated **before** the example css files are loaded

Screenshot 1 - the iframe is to high when the items are floating:  
![iframe to high with floating items](http://i.imgur.com/ZhZE1we.png)

Screenshot 2 - when I remove the float from the items, the height fits:  
![iframe fits](http://i.imgur.com/Euvj96I.png)

**Comment by asifshirazi** [comment]
I have only a div with the height of **73px** in body, but on iframe it calculates **298px**.

![screen shot 2016-01-25 at 3 06 36 pm](https://cloud.githubusercontent.com/assets/7354813/12548031/715c4464-c375-11e5-948f-92c045ea675d.png)

**Comment by jonathantneal** [comment]
The calculation is handled `onload` and then reoccurs on a 1/3 second `interval`. https://github.com/jonathantneal/mdcss-theme-github/blob/gh-pages/assets/examples.js#L134-L138

Would you provide more details for your example? I am happy to look into the issue.

**Comment by asifshirazi** [comment]
If you have too many blocks elements or unordered list in your `example:html` then you can see this issue, basically he calculates `iframe` height before my css files are loaded.
If I comment _line.136_ of **examples.js**, then this will works fine, but I know this is not the right solution.

**Comment by jonathantneal** [comment]
Ah! So, the issue is that the iframe has issues sizing back down. Thanks, I will work on this.

**Comment by asifshirazi** [comment]
One more thing that I want to share related with this bug,
If you select the **iframe** dom in chrome inspector and uncheck the height, 
then from **example.js** > `setInterval(resize, 334);` will calculate the final height which is accurate.

![iframe-height](https://cloud.githubusercontent.com/assets/7354813/12696392/7fb010ee-c78b-11e5-9f31-9f0565b400d6.gif)

**Comment by sfinevelir** [comment]
I had the same issue, and—probably not the best solution, but—I was able to resolve it by wrapping the contents of the `<iframe>` body in a `<div>`, then using that to detect height changes instead of the `<iframe>` itself. Since the wrapper div doesn't have a fixed height, it shrinks/grows with the contents, independent of the `<iframe>` fixed height.

In [example.js](https://github.com/jonathantneal/mdcss-theme-github/blob/gh-pages/assets/examples.js) around line 115:

`idoc.body.innerHTML = '<div class="iframe-wrapper">' + idoc.body.innerHTML + '</div>';`

and at line 123 inside the `resize()` function just below that:

`var currentScrollHeight = documentElement.getElementsByClassName('iframe-wrapper')[0].offsetHeight;`

I haven't tested this for more than a few minutes, but it seems to work if I shrink or stretch the window, and doesn't cause my CPU to thrash. A good start? `¯\_(ツ)_/¯`

**Comment by maoberlehner** [comment]
What I have done to "solve" the problem in my custom mdcss theme:
I removed https://github.com/jonathantneal/mdcss-theme-github/blob/gh-pages/assets/examples.js#L134-L138
and added https://github.com/avalanchesass/avalanche_mdcss_theme/blob/dev/assets/examples.js#L135-L137

So far it works flawless for me.

**Comment by stephenway** [comment]
Added last week to mdcss-theme-github

**Comment by davidhund** [comment]
@stephenway — I just noticed I get `Uncaught TypeError: resize is not a function` for https://github.com/jonathantneal/mdcss-theme-github/blob/gh-pages/assets/examples.js#L148 and (therefore) the iframes are not (re)sized correctly.

**Comment by jarodtaylor** [comment]
resize() is a reserved javascript function. You'll get an error in your console.

I've also noticed that the `addEventListener('load')` functions in the `examples.js` file do not work on `iframes` following the first one (or two). You'll see when you inspect element that the `iframes` aren't getting height styles AND the `html` and `body` tags aren't getting the styles.
